{
  sudo: "required",
  dist: "trusty",
  addons: {
    apt: {
      sources: ["google-chrome"],
      packages: ["google-chrome-stable"]
    }
  },
  language: "node_js",
  node_js: ["8", "10"],
  cache: {
    directories: ["node_modules"]
  },
  before_cache: [
    "rm -rf node_modules/.cache"
  ]
}
